[phases.setup]
nixPkgs = [
  "...",
  "chromium",
  "chezmoi",
  "curl",
  "fd",
  "fzf",
  "gcc",
  "gh",
  "git",
  "git-filter-repo",
  "gnumake",
  "jq",
  "less",
  "micro",
  "pkg-config",
  "python3",
  "ripgrep",
  "rsync",
  "tree",
  "unzip",
  "yq-go",
  "zip",
]
aptPkgs = [
  "bash-completion",
  "ca-certificates",
  "dnsutils",
  "iproute2",
  "iputils-ping",
  "lsof",
  "openssh-client",
  "procps",
]

[phases.build]
cmds = ["bash scripts/install-git-wrangler.sh"]

[start]
cmd = "bash scripts/start.sh"
