[variables]
FONTCONFIG_FILE = "/root/.nix-profile/etc/fonts/fonts.conf"
FONTCONFIG_PATH = "/root/.nix-profile/etc/fonts"
LIBGL_DRIVERS_PATH = "/root/.nix-profile/lib/dri"
XDG_DATA_DIRS = "/root/.nix-profile/share:/usr/local/share:/usr/share"

[phases.setup]
nixPkgs = [
  "...",
  "chromium",
  "chezmoi",
  "curl",
  "fd",
  "fontconfig.out",
  "fzf",
  "gcc",
  "gh",
  "git",
  "git-filter-repo",
  "gnumake",
  "jq",
  "less",
  "micro",
  "mesa.drivers",
  "nixpacks",
  "pkg-config",
  "python3",
  "ripgrep",
  "rsync",
  "tree",
  "unzip",
  "uv",
  "yq-go",
  "zip",
]
nixLibs = [
  "...",
  "libxkbcommon",
  "mesa.drivers",
  "vulkan-loader",
  "xorg.libX11",
  "xorg.libXcursor",
  "xorg.libXi",
  "xorg.libXrandr",
]
aptPkgs = [
  "bash-completion",
  "ca-certificates",
  "dnsutils",
  "iproute2",
  "iputils-ping",
  "lsof",
  "openssh-client",
  "procps",
  "xdotool",
  "xvfb",
]

[phases.build]
cmds = ["bash scripts/install-git-wrangler.sh"]

[start]
cmd = "bash scripts/start.sh"
